### ISSUE TITLE
issue in ubuntu 20.04 GLIBCXX_3.4.29

### ISSUE THREAD

**Issue by hidalgoem** [clariusdev/cast#113]
Hi guys,

Trying to run the pysidecaster.py example on Ubuntu 20.04 with python 3.8, but couldn't. I put all the files in one folder and then run the command LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. python3 pysidecaster.py from the terminal. I used the last update posted last week(v10.2.2). Including the pycast.so and pyclariuscast.so available for Ubuntu 20 and python 3.8. This is what I got:

auro@MauroLinux:~/CLARIUS PROBE CODE/cast-10.2.2/desktop/src/python$ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. python3 pysidecaster.py
Traceback (most recent call last):
  File "pysidecaster.py", line 6, in <module>
    import pyclariuscast
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/mauro/CLARIUS PROBE CODE/cast-10.2.2/desktop/src/python/pyclariuscast.so)

Any clue what is happening and what can I do to fix it?
Thanks

**Comment by clariusk** [comment]
might be some useful info here: https://github.com/clariusdev/cast/issues/103, otherwise a few of the other closed issues also discuss this. thanks

**Comment by hidalgoem** [comment]
Hi, I tried by using the ctypes impport as suggested but is not working. same issue:

Traceback (most recent call last):
  File "/home/mauro/PycharmProjects/CLAROIUS_CAST2/pysidecaster.py", line 8, in <module>
    pyclariuscast = ctypes.cdll.LoadLibrary('./pyclariuscast.so') # load the pyclariuscast.so shared library
  File "/usr/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./pyclariuscast.so)

In windows is working fine, but I need this working in Ubuntu. Any idea what is happening?

**Comment by clariusk** [comment]
a few threads i was able to dig up with same issue:
- https://stackoverflow.com/questions/49875588/importerror-lib64-libstdc-so-6-version-cxxabi-1-3-9-not-found
- https://stackoverflow.com/questions/58424974/anaconda-importerror-usr-lib64-libstdc-so-6-version-glibcxx-3-4-21-not-fo
