### ISSUE TITLE
Error: undefined symbol: eglDestroyImage

### ISSUE THREAD

**Issue by MrWenhaoY** [clariusdev/cast#168]
When running any of the example python scripts, the following error occurs:

```
Traceback (most recent call last):
  File "/home/ubuntu/src/cast-11.2.0/examples/python/pysidecaster.py", line 11, in <module>
    pyclariuscast = ctypes.cdll.LoadLibrary("./pyclariuscast.so") # load the pyclariuscast.so shared library
  File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLIbrary
    return self._dlltype(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./pyclariuscast.so: undefined symbol: eglDestroyImage
```

**Environment:**
Python version is 3.10.12
Ubuntu version is 22.04.3
Linux is aarch64
I made sure that both libcast.so and pyclariuscast.so were in the same folder as the scripts. I used the cast-11.2.0-linux.aarch64-gcc_ubuntu_22.04.zip release and the pyclariuscast.so in the python310 folder

**Comment by clariusk** [comment]
You'll probably want to ensure your system has the EGL package(s) installed

**Comment by MrWenhaoY** [comment]
I have checked the required dependencies using `ldd pyclariuscast.so` and I have all the dependencies. The only one referencing EGL was `libwayland-egl.so.1 => /lib/aarch64-linux-gnu/libwayland-egl.so.1`. I also tried installing the following packages:

```
libwayland-egl-backend-dev
libwayland-egl1 (already installed)
libwayland-egl1-mesa
libwayland-egl++0
libegl-dev (already installed)
libegl-mesa0
libnvidia-egl-wayland-dev
libnvidia-egl-wayland1 (already installed)
libgegl-dev
libghc-hledger-dev
```

However, the issue still persists (`OSError: ./pyclariuscast.so: undefined symbol: eglDestroyImage`)

**Comment by MrWenhaoY** [comment]
@clariusk Would you have time for a Zoom meeting about this either this afternoon or tomorrow afternoon? (Anytime 1-4PM EDT or 10-1 PDT)

**Comment by clariusk** [comment]
have you tried a non-ARM version of Ubuntu to see if the issue exists on an x86 platform as well

**Comment by MrWenhaoY** [comment]
The exact issue does not exist on x86, ubuntu 20.04. However, on that version, there is a similar issue: `AttributeError: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: dlclose` but that issue only occurs upon quit so the examples still run.

**Comment by clariusk** [comment]
thanks, as we do not test on all the variants for linux platforms, and only provide builds it will be difficult for us to pinpoint the problem, the other method you could try is compiling the C++ program rather than the python wrapper

**Comment by jonortega77** [comment]
> The exact issue does not exist on x86, ubuntu 20.04. However, on that version, there is a similar issue: `AttributeError: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: dlclose` but that issue only occurs upon quit so the examples still run.

I am having this problem but i don't know how to solve it. 

Any help is appreciated !

Error log:
```bash
initialization succeeded
Attempting to connect to 172.31.83.215 on port 5000
connection failed
Traceback (most recent call last):
  File "/home/src/monai/pycaster.py", line 251, in <module>
    main()
  File "/home/src/monai/pycaster.py", line 200, in main
    libc.dlclose(libcast_handle)
    ^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 389, in __getattr__
    func = self.__getitem__(name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 394, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: /lib/x86_64-linux-gnu/libc.so.6: undefined symbol: dlclose
Segmentation fault (core dumped)
```

Docker container shared library verification:

![image](https://github.com/user-attachments/assets/08823a41-f502-4921-83c5-0bf44dd88fd2)


pycaster.py

```python
#!/usr/bin/env python

import argparse
import ctypes
import os.path
import sys
from PIL import Image
import pyigtl
import time

if sys.platform.startswith("linux"):
    libcast_handle = ctypes.CDLL('/home/src/monai/libcast.so', ctypes.RTLD_GLOBAL)._handle  # load the libcast.so shared library
    pyclariuscast = ctypes.cdll.LoadLibrary('/home/src/monai/pyclariuscast.so')  # load the pyclariuscast.so shared library

# once the shared libraries (libcast.so and pyclariuscast.so) we need to import them 

# import libcast_handle
import pyclariuscast

printStream = True


client = None # Initialize the OpenIGTLink client
connected_2_server = False # Initialize the connection status to the OpenIGTLink server

counter = 1
img_counter = 1

## called when a new processed image is streamed
# @param image the scan-converted image data
# @param width width of the image in pixels
# @param height height of the image in pixels
# @param sz full size of image
# @param micronsPerPixel microns per pixel
# @param timestamp the image timestamp in nanoseconds
# @param angle acquisition angle for volumetric data
# @param imu inertial data tagged with the frame
def newProcessedImage(image, width, height, sz, micronsPerPixel, timestamp, angle, imu):
    global counter
    global img_counter
    bpp = sz / (width * height)
    if printStream:
        print(
            "image: {0}, {1}x{2} @ {3} bpp, {4:.2f} um/px, imu: {5} pts".format(
                timestamp, width, height, bpp, micronsPerPixel, len(imu)
            ),
            end="\r",
        )
    if bpp == 4:
        img = Image.frombytes("RGBA", (width, height), image)
    else:
        img = Image.frombytes("L", (width, height), image)
    # img.save("processed_image.png")
    if counter % 15 == 0:
        # send_img_to_server(img)
        print(f"sending: ", img_counter)
        img_counter += 1
    counter += 1

    return

def send_img_to_server(img):

    global connected_2_server  # Ensure the global variable is used
    global client  # Ensure the global variable is used


    if client is None:
        # Create an OpenIGTLink client to send the image to the server
        client = pyigtl.OpenIGTLinkClient(host='localhost', port=18944)
        print(f"Client: {client.host} , {client.port}")

    if not connected_2_server:
        # Connect to the OpenIGTLink server
        while not client.is_connected():
            print("Failed to connect to OpenIGTLink server. Retrying...")
            time.sleep(1)  # Wait for 1 second before retrying to connect to the OpenIGTLink server

        connected_2_server = True
        print("Connected to OpenIGTLink server")

    if connected_2_server:

        img_message = pyigtl.ImageMessage(image=img, device_name="UltrasoundImage")


        if img_message._valid_message:
            print("Sending image to OpenIGTLink server")
            # Send the image to the OpenIGTLink server
            client.send_message(img_message)

        else:
            print("Message must be derived from MessageBase class")


## called when a new raw image is streamed
# @param image the raw pre scan-converted image data, uncompressed 8-bit or jpeg compressed
# @param lines number of lines in the data
# @param samples number of samples in the data
# @param bps bits per sample
# @param axial microns per sample
# @param lateral microns per line
# @param timestamp the image timestamp in nanoseconds
# @param jpg jpeg compression size if the data is in jpeg format
# @param rf flag for if the image received is radiofrequency data
# @param angle acquisition angle for volumetric data
def newRawImage(image, lines, samples, bps, axial, lateral, timestamp, jpg, rf, angle):
    # check the rf flag for radiofrequency data vs raw grayscale
    # raw grayscale data is non scan-converted and in polar co-ordinates
    # print(
    #    "raw image: {0}, {1}x{2} @ {3} bps, {4:.2f} um/s, {5:.2f} um/l, rf: {6}".format(
    #        timestamp, lines, samples, bps, axial, lateral, rf
    #    ), end = "\r"
    # )
    # if jpg == 0:
    #    img = Image.frombytes("L", (samples, lines), image, "raw")
    # else:
    #    # note! this probably won't work unless a proper decoder is written
    #    img = Image.frombytes("L", (samples, lines), image, "jpg")
    # img.save("raw_image.jpg")
    return


## called when a new spectrum image is streamed
# @param image the spectral image
# @param lines number of lines in the spectrum
# @param samples number of samples per line
# @param bps bits per sample
# @param period line repetition period of spectrum
# @param micronsPerSample microns per sample for an m spectrum
# @param velocityPerSample velocity per sample for a pw spectrum
# @param pw flag that is true for a pw spectrum, false for an m spectrum
def newSpectrumImage(image, lines, samples, bps, period, micronsPerSample, velocityPerSample, pw):
    return


## called when a new imu data is streamed
# @param imu inertial data tagged with the frame
def newImuData(imu):
    return


## called when freeze state changes
# @param frozen the freeze state
def freezeFn(frozen):
    if frozen:
        print("\nimaging frozen")
    else:
        print("imaging running")
    return


## called when a button is pressed
# @param button the button that was pressed
# @param clicks number of clicks performed
def buttonsFn(button, clicks):
    print("button pressed: {0}, clicks: {1}".format(button, clicks))
    return


## main function
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--address", "-a", dest="ip", help="ip address of probe.", required=True)
    parser.add_argument("--port", "-p", dest="port", type=int, help="port of the probe", required=True)
    parser.add_argument("--width", "-w", dest="width", type=int, help="image output width in pixels")
    parser.add_argument("--height", "-ht", dest="height", type=int, help="image output height in pixels")
    parser.set_defaults(ip=None)
    parser.set_defaults(port=None)
    parser.set_defaults(width=640)
    parser.set_defaults(height=480)
    args = parser.parse_args()

    # uncomment to get documentation for pyclariuscast module
    # print(help(pyclariuscast))

    if not args.ip or not args.port or args.port < 0:
        print("one or more arguments are invalid")
        parser.print_usage()
        return

    # get home path
    path = os.path.expanduser("~/")

    # initialize
    cast = pyclariuscast.Caster(newProcessedImage, newRawImage, newSpectrumImage, newImuData, freezeFn, buttonsFn)
    ret = cast.init(path, args.width, args.height)
    if ret:
        print("initialization succeeded")
        print("Attempting to connect to {0} on port {1}".format(args.ip, args.port))
        ret = cast.connect(args.ip, args.port, "research")
        if ret:
            print("connected to {0} on port {1}".format(args.ip, args.port))
        else:
            print("connection failed")
            if sys.platform.startswith("linux"):
                # unload the shared library before destroying the cast object
                ctypes.CDLL("libc.so.6").dlclose(libcast_handle)
            cast.destroy()
            return
    else:
        print("initialization failed")
        return

    # input loop
    key = ""
    while key != "q" and key != "Q":
        key = input("press (q)->quit (a)->action (s)->stream (p)->param change: ")
        if key == "a" or key == "A":
            key = input("(f)->freeze (i)->capture image (c)->capture cine, (d/D)->depth, (g/G)->gain: ")
            if key == "f" or key == "F":
                cast.userFunction(1, 0)
            elif key == "i" or key == "I":
                cast.userFunction(2, 0)
            elif key == "c" or key == "C":
                cast.userFunction(3, 0)
            elif key == "d":
                cast.userFunction(4, 0)
            elif key == "D":
                cast.userFunction(5, 0)
            elif key == "g":
                cast.userFunction(6, 0)
            elif key == "G":
                cast.userFunction(7, 0)
        elif key == "d" or key == "D":
            ret = cast.disconnect()
            if ret:
                print("successful disconnect")
            else:
                print("disconnection failed")
        elif key == "s" or key == "S":
            global printStream
            printStream = not printStream
        elif key == "p" or key == "P":
            inp = input("enter: {parameter name} {value [float/true/false]}").split()
            if len(inp) != 2:
                print("please format as: {parameter name} {value [float/true/false]}")
            else:
                if inp[1] == "true" or inp[1] == "false":
                    cast.enableParam(inp[0], 1 if inp[1] == "true" else 0)
                else:
                    cast.setParam(inp[0], float(inp[1]))

    cast.destroy()


if __name__ == "__main__":
    main()
```
