### ISSUE TITLE
AttributeError: pyclariuscast.so: undefined symbol: Caster

### ISSUE THREAD

**Issue by jonortega77** [clariusdev/cast#178]
Hi there,

I am trying to use the pycaster in a Docker container running on Ubuntu 20.04. My host machine is running Windows 11, and the following error occurred when I tried running the script:

```bash
root@d8296747e470:/home/src# python3 pycaster.py -a 127.0.0.1 -p 5828
Traceback (most recent call last):
  File "/home/src/pycaster.py", line 252, in <module>
    main()
  File "/home/src/pycaster.py", line 191, in main
    cast = pyclariuscast.Caster(newProcessedImage, newRawImage, newSpectrumImage, newImuData, freezeFn, buttonsFn)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 389, in __getattr__
    func = self.__getitem__(name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 394, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: /home/src/pyclariuscast.so: undefined symbol: Caster
```

## Environment:

- Docker container using Ubuntu 20.04
- Running on Windows 11 host
- Python 3.11.11
- pycaster.py script fails to locate the Caster symbol in the pyclariuscast.so shared object.

### Build the Docker image and run it.

```Dockerfile
# Base image
FROM ubuntu:20.04

# Avoid prompts from apt
ENV DEBIAN_FRONTEND=noninteractive

RUN mkdir -p /home/src/

WORKDIR /home/src/

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    libblkid1 \
    libbrotli1 \
    libglib2.0-0 \
    libssl-dev \
    wget \
    python3.11 \
    python3.11-dev \
    python3.11-distutils \
    python3-pip \
    tzdata \
    libegl1-mesa \
    libdbus-1-3 \
    libpulse0 \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav \
    gstreamer1.0-gl \
    gstreamer1.0-tools \
    gstreamer1.0-x \
    libgstreamer-gl1.0-0 \
    libopengl0 \
    libgl1 \
    libxkbcommon-x11-0 \
    libx11-6 \
    libxcb1 \
    libxcb-glx0 \
    libxcb-render0 \
    libxcb-shape0 \
    libxcb-xfixes0 \
    libxcb-cursor0 \
    libxcb-keysyms1 \
    libxcb-icccm4 \
    libxcb-image0 \
    libxcb-shm0 \
    libxcb-randr0 \
    libxcb-sync1 \
    libxcb-xkb1 \
    libxkbcommon0 \
    libxkbcommon-x11-0 \
    libsm6 \
    libice6 \
    libfontconfig1 \
    libfreetype6 \
    libexpat1 \
    # Add GCC and development tools
    gcc \
    g++ \
    software-properties-common \
    && add-apt-repository ppa:ubuntu-toolchain-r/test \
    && apt-get update \
    && apt-get install -y libstdc++6 \
    && rm -rf /var/lib/apt/lists/*

# Update alternatives to set Python 3.11 as default
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1 \
    && update-alternatives --set python3 /usr/bin/python3.11

# Install pip and build dependencies
RUN wget https://bootstrap.pypa.io/get-pip.py \
    && python3.11 get-pip.py \
    && rm get-pip.py \
    && pip3 install --upgrade pip setuptools wheel

# Install Python packages
RUN pip3 install Pillow pyigtl

# Install specific version of ICU library
RUN wget http://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu66_66.1-2ubuntu2_amd64.deb \
    && dpkg -i libicu66_66.1-2ubuntu2_amd64.deb \
    && rm libicu66_66.1-2ubuntu2_amd64.deb

# Copy necessary files into the container
COPY pyclariuscast.so /home/src/
COPY libcast.so /home/src/

# Set LD_LIBRARY_PATH to include /home/src/ for shared libraries
ENV LD_LIBRARY_PATH=/home/src:${LD_LIBRARY_PATH:-}

# Expose port
EXPOSE 5000

# Default command
CMD ["python3", "pycaster.py"]
```
Execute the pycaster.py script with the required arguments:

```bash
python3 pycaster.py -a 127.0.0.1 -p 5828
```

Any help would be appreciated !!

PD: The downloaded binaries are "cast-11.2.0-linux.x86_64-gcc_ubuntu_20.04"

**Comment by jonortega77** [comment]
any updates here ? :)

**Comment by julien-l** [comment]
Hello you probably have the incorrect binaries, try to use the asset file [cast-11.2.0-linux.aarch64-gcc_ubuntu_20.04.zip](https://github.com/clariusdev/cast/releases/download/v11.2.0/cast-11.2.0-linux.aarch64-gcc_ubuntu_20.04.zip).

----

Details: I used the Docker file you posted and was able to reproduce the same error ("missing file"). Then I opened a bash prompt (instead of starting the python script with `CMD`) and checked the container's architecture:

    docker build -t clarius/cast .
    docker run --name clarius-cast -it clarius/cast bash
    $ uname -a
    Linux b2e5c03f2891 6.10.14-linuxkit #1 SMP Thu Oct 24 19:28:55 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

My architecture is aarch64, not x86_64. I used the appropriate asset and the script ran properly. The python's error message is misleading, it states the file is missing instead of telling us the file has the wrong architecture.
